// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

public class AutoLauncher
{
	private static AutoLauncher s_instance;
	
	private bool m_autoLaunch;
	
	public static AutoLauncher Instance ()
	{
		if (s_instance == null) {
			s_instance = new AutoLauncher ();
		}
		
		return s_instance;
	}
	
	private AutoLauncher ()
	{
		m_autoLaunch = false;
	}
	
	public bool AutoLaunch ()
	{
		return m_autoLaunch;
	}
	
	public void SetAutoLaunch (bool autoLaunch)
	{
		m_autoLaunch = autoLaunch;
	}
	
	public void ValidateAutoLauncher (string applicationState)
	{
		if (applicationState == null) {
			// undefined application state
			Debug.Log ("ValidateAutoLauncher - undefined application state");
			return;
		}
		
		if (applicationState.Equals("inactive")) {
			// application was launched fresh from a notification
			// auto launch on transition to the main menu
		} else if (applicationState.Equals("active")) {
			// application in foreground when notification was received
			// do nothing, require explicit launch from the user
			// next launch will handle the latest received notification context
			return;
		} else if (applicationState.Equals("background")) {
			if (Application.loadedLevelName.Equals ("MainMenu")) {
				// application came from background and on main menu
				// immediately launch

				GameObject fuelHandlerObject = GameObject.Find("FuelHandlerObject");
				FuelHandler fuelHandler = fuelHandlerObject.GetComponent<FuelHandler>();
				fuelHandler.launchPropeller();

				return;
			} else {
				// application came from background and NOT on main menu
				// transition to the main menu and auto launch when ready

				Application.LoadLevel("MainMenu");
			}
		} else {
			Debug.Log ("ValidateAutoLauncher - invalid application state: " + applicationState);
			// invalid application state
			return;
		}
		
		SetAutoLaunch (true);
	}
}