#!/bin/bash

currentDirectory=`pwd`
xcodeDirectory=`xcode-select -p`

python "$currentDirectory/Assets/Propeller/PostbuildScripts/PropellerBuild.py" "$currentDirectory/Assets/Plugins/iOS/" "$xcodeDirectory" "$1" "$2" $3
